#!/bin/bash

# extract_subgraph_sequences.sh
# Usage: ./extract_subgraph_sequences.sh -f input.fasta -g graph.gfa -d output_dir -n 2 -L 1000 -r long

usage() {
    echo "Usage: $0 -f <fasta_file> -g <gfa_file> -d <output_dir> [-n <node_steps>] [-L <bp_steps>] -r <read_type: short|long>"
    exit 1
}

# Initialize variables
FASTA_FILE=""
GFA_FILE=""
OUTPUT_DIR=""
CONTEXT_STEPS="" # Default handled in logic
CONTEXT_BP=""
READ_TYPE="long"

# Parse arguments
while getopts ":f:g:d:n:L:r:h" opt; do
    case ${opt} in
        f ) FASTA_FILE=$OPTARG ;;
        g ) GFA_FILE=$OPTARG ;;
        d ) OUTPUT_DIR=$OPTARG ;;
        n ) CONTEXT_STEPS=$OPTARG ;;
        L ) CONTEXT_BP=$OPTARG ;;
        r ) READ_TYPE=$OPTARG ;;
        h ) usage ;;
        * ) usage ;;
    esac
done

if [[ -z "$FASTA_FILE" || -z "$GFA_FILE" || -z "$OUTPUT_DIR" ]]; then
    echo "Error: Missing required arguments."
    usage
fi

# Locate helper scripts
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROCESS_GAF_SCRIPT="${SCRIPT_DIR}/process_gaf.py"
EXTRACT_SUBGRAPH_SCRIPT="${SCRIPT_DIR}/extract_subgraphs.sh"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"
GAF_FILE="$OUTPUT_DIR/alignment.gaf"

echo "=========================================="
echo "Starting Sequence Alignment Extraction"
echo "Fasta: $FASTA_FILE"
echo "Read Type: $READ_TYPE"
echo "=========================================="

# ---------------------------------------------------------
# 1. Align Sequences to Graph
# ---------------------------------------------------------
if [ "$READ_TYPE" == "short" ]; then
    echo "Aligning using vg giraffe sr..."
    BASE_NAME="${GFA_FILE%.*}"
    vg giraffe -Z "${BASE_NAME}.giraffe.gbz" -m "${BASE_NAME}.shortread.withzip.min" -d "${BASE_NAME}.dist" -f "$FASTA_FILE" -o gaf > "$GAF_FILE"
else
    echo "Aligning using vg giraffe lr..."
    vg giraffe -Z "${BASE_NAME}.giraffe.gbz" -m "${BASE_NAME}.longread.withzip.min" -d "${BASE_NAME}.dist" -f "$FASTA_FILE" -o gaf > "$GAF_FILE"
fi

if [[ ! -s "$GAF_FILE" ]]; then
    echo "Error: Alignment produced empty GAF file."
    exit 1
fi

# ---------------------------------------------------------
# 2. Process GAF to identify Hits
# ---------------------------------------------------------
echo "Processing GAF file to extract hits..."
if [ -f "$PROCESS_GAF_SCRIPT" ]; then
    python3 "$PROCESS_GAF_SCRIPT" "$GAF_FILE" "$OUTPUT_DIR"
else
    echo "Error: process_gaf.py not found at $PROCESS_GAF_SCRIPT"
    exit 1
fi

# ---------------------------------------------------------
# 3. Extract Subgraphs & Generate Manifest
# ---------------------------------------------------------
echo "Extracting subgraphs for hits..."
JSON_FILE="$OUTPUT_DIR/hits.json"
echo "[" > "$JSON_FILE"
FIRST_ENTRY=true

# Iterate over hit files generated by process_gaf.py
for NODE_FILE in "$OUTPUT_DIR"/*_hit.txt; do
    [ -e "$NODE_FILE" ] || continue
    
    # Read the comma-separated list of nodes
    NODES=$(head -n 1 "$NODE_FILE")
    HIT_NAME=$(basename "$NODE_FILE" _hit.txt)
    OUTPUT_PREFIX="$OUTPUT_DIR/$HIT_NAME"
    echo "Processing hit: $HIT_NAME"

    # Prepare command arguments for extraction
    CMD_ARGS=(
        "-i" "$GFA_FILE"
        "-o" "${OUTPUT_PREFIX}.og"
        "-l" "$NODES"
        "--odgi"
        "--bandage"
    )

    # Context logic: Priority to BP (-L) if set, otherwise Steps (-c)
    if [[ -n "$CONTEXT_BP" ]]; then
        CMD_ARGS+=("-L" "$CONTEXT_BP")
        echo "  Context: $CONTEXT_BP bp"
    elif [[ -n "$CONTEXT_STEPS" ]]; then
        CMD_ARGS+=("-c" "$CONTEXT_STEPS")
        echo "  Context: $CONTEXT_STEPS nodes"
    else
        # Default fallback
        CMD_ARGS+=("-c" "1")
        echo "  Context: Default (1 node)"
    fi

    # Run extraction
    bash "$EXTRACT_SUBGRAPH_SCRIPT" "${CMD_ARGS[@]}"

    # JSON Manifest Generation
    if [ "$FIRST_ENTRY" = true ]; then
        FIRST_ENTRY=false
    else
        echo "," >> "$JSON_FILE"
    fi
    
    ODGI_IMG="${HIT_NAME}_odgi.png"
    BANDAGE_IMG="${HIT_NAME}_bandage.svg"

    cat <<EOF >> "$JSON_FILE"
    {
        "id": "$HIT_NAME",
        "nodes": "$NODES",
        "odgi_image": "$ODGI_IMG",
        "bandage_image": "$BANDAGE_IMG"
    }
EOF

done

echo "]" >> "$JSON_FILE"
echo "Extraction complete. Manifest saved to $JSON_FILE"